version: '3.9'

services:
  db:
    container_name: DB-Server
    image: postgres
    env_file:
      - ./backend/.env 
    ports:
        - "5433:5432"

  backend:
    container_name: Back-End-Server
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "
        python manage.py migrate &&
        python manage.py test &&
        python manage.py runserver 0.0.0.0:8000"
        
    volumes:
      - .:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env 
    restart: on-failure

  frontend:
    container_name: Front-End-Server
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  
    depends_on:
      - backend 

networks:
  custom_network:
    driver: bridge
